name: lugarenos
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.7
  cloud_firestore_web: ^2.6.7
  cupertino_icons: ^1.0.2
  firebase: ^9.0.2
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  flutter:
    sdk: flutter
  geocoding: ^2.0.2
  geolocator: ^8.1.1
  google_maps_flutter: ^2.1.1
  google_maps_utils: ^1.5.0+0
  google_sign_in: ^5.2.3
  http: ^0.13.4
  image_picker: ^0.8.4+8
  image_picker_for_web: ^2.1.5
  flutter_rating_bar: ^4.0.0

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: AmazingSlabTrial-Bold
      fonts:
        - asset: assets/fonts/Amazing-Slab-Bold-trial.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
